name: Earn points daily

on:
  # 定时器触发：
  schedule:
    # 每天的9:11执行（UTC时间，尽量不要采用整点而是较为随意的时间，且出现延后是正常的）
    - cron: '11 1 * * *'
  # 手动触发：
  workflow_dispatch:

jobs:
  earn_points:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - name: Earn points
        run: python ./main.py
